# "RIR_estimator" CONFIG FILE

data_dir: './data/'
sampling_rate: 16000

# CORPUS GENERATION PARAMETERS:

material_index: './resources/materials_index_pra.csv'
dirac: './data/diracs/burst_balloon.wav'
rir_dir: './data/rir_clips/'
corpus_file: './data/full_corpus.csv'

corpus_samples: 10000


# TRAINING PARAMETERS:
batch_train: 32
batch_test: 16

lr: 0.001
epochs: 5

num_workers: 1
