####################################################
#           RIR ESTIMATOR CONFIG FILE              #
####################################################

data_dir: './data/'
results_dir: './results/'
sampling_rate: 16000

#####################################################
#          CORPUS GENERATION PARAMETERS:            #
#####################################################

material_index: './utils/materials_index_pra.csv'
dirac: './data/diracs/burst_balloon.wav'
rir_dir: './data/rir_clips/'

corpus_file: './data/full_corpus.csv'
corpus_samples: 10000

# Room dimensions
x_min: 1.5
x_max: 20

y_min: 1.5
y_max: 20

z_min: 2.5
z_max: 10


#####################################################
#              TRAINING PARAMETERS:                 #             
#####################################################

multi-task: True
loss_weight_abspt: 0.95
loss_weight_geom: 0.05

batch_train: 32
batch_test: 16

lr: 0.001
epochs: 1 #42

num_workers: 1
